Repository EOSIO/eosio-explorer, pull requests merged in 2019-05, with the labels that each got.

#87 Update README.md .. Fixed path: ~/.bash_profile
  README.md
Labels: documentation

#88 Fogbugz 3426: Kill and restart the process in pm2
  pm2.js
Labels: enhancement

#89 Fogbugz 3442 - Handle docker volumes after restart
  README.md
  cli.sh
  config.file
  init_config.file
  scripts/start.sh
  scripts/start_gui.sh
  scripts/stop_dockers.sh
Labels: bug, enhancement

#91 Remove unnecessary dependencies
  package.json
  src/scss/style.scss
  yarn.lock
Labels: enhancement

#90 Fogbugz 3443 - In production mode, serve the app to user without building GUI while init
  README.md
  package.json
  scripts/init.sh
  scripts/start.sh
  scripts/start_gui.sh
  serve.js
  src/index.js
  yarn.lock
Labels: enhancement

#92 Fogbugz 3447 - Add footer with Privacy Policy link
  .env
  src/app/App.jsx
  src/components/ConsoleLogger/ConsoleLogger.scss
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.scss
  src/components/Footer/index.js
  src/components/index.js
  src/pages/PrivacyPolicyPage/PrivacyPolicyPage.jsx
  src/pages/PrivacyPolicyPage/PrivacyPolicyPage.scss
  src/pages/PrivacyPolicyPage/index.js
  src/pages/TermsOfUsePage/TermsOfUsePage.jsx
  src/pages/TermsOfUsePage/TermsOfUsePage.scss
  src/pages/TermsOfUsePage/index.js
  src/scss/style.scss
  src/templates/StandardTemplate/StandardTemplate.jsx
Labels: enhancement

#93 Doc: add Analytics section.
  README.md
Labels: documentation

#94 Prepare push to npm with only build related files.
  .env
  README.md
  helpers/README.md
  helpers/openBrowser.js
  package.json
  scripts/init.sh
  scripts/start.sh
  scripts/start_gui.sh
  serve.js
  yarn.lock
Labels: documentation, enhancement

#95 Move styled-components dependencies from eosio-toppings to here.
  package.json
Labels: enhancement

#96 Align Console Logger to page padding.
  src/components/ConsoleLogger/ConsoleLogger.scss
Labels: enhancement

#97 Remove legacy code which only used for npm private package.
  scripts/init.sh
  scripts/remove_dockers.sh
  scripts/start.sh
  scripts/start_gui.sh
Labels: enhancement

#100 Fogbugz 3411: Improper not found styling on Action Detail Page
  src/pages/ActiondetailPage/ActiondetailPage.jsx
  src/pages/ActiondetailPage/components/Actiondetail/Actiondetail.jsx
  src/pages/ActiondetailPage/components/Actionjson/Actionjson.jsx
Labels: bug

#104 Fogbugz 3419 - Error Console going off screen
  src/components/ConsoleLogger/ConsoleLogger.scss
Labels: bug

#101 Fogbugz 3425 - Deployment Page responsive CSS issues
  src/pages/DeploymentPage/DeploymentPage.jsx
  src/styled/DropdownStyled.js
Labels: bug

#103 Fogbugz 3428: Help button not linking to context sensitive help
  src/components/HelpFAB/HelpFAB.jsx
Labels: enhancement

#102 Fogbugz 3431 - Action history loading spinner
  src/pages/PushactionPage/PushactionPageReducer.js
  src/pages/PushactionPage/components/Actionhistory.jsx
Labels: bug

#99 Move dotenv package back into "dependencies" for production build.
  package.json
Labels: bug

#105 Fogbugz 3422 - Push Action: There is no sorting on filter by smart contract
  src/pages/PushactionPage/components/Actionhistory.jsx
Labels: bug

#106 Refactor all pollingEpic by using exhaustMap
  src/pages/BlocklistPage/components/Blocklist/BlocklistReducer.js
  src/pages/TransactionlistPage/components/Transactionlist/TransactionlistReducer.js
  src/reducers/headblock.js
  src/reducers/lastblockinfo.js
Labels: enhancement

#107 Fogbugz 3457 - Compiler service dev mode
  scripts/start_gui.sh
Labels: bug

#108 Fogbugz 3434 - Update timestamp colums
  src/pages/ActiondetailPage/components/Actiondetail/Actiondetail.jsx
  src/pages/ActionlistPage/components/Actionlist/Actionlist.jsx
  src/pages/BlocklistPage/components/Blocklist/Blocklist.jsx
  src/pages/PushactionPage/components/Actionhistory.jsx
  src/pages/TransactionlistPage/components/Transactionlist/Transactionlist.jsx
Labels: enhancement

#110 Adjustments to in-app console log terminal
  src/components/ConsoleLogger/ConsoleLogger.jsx
  src/helpers/error-logger.js
Labels: bug, enhancement

#111 Removing init option from start command
  README.md
  scripts/start.sh
Labels: documentation
