Repository EOSIO/eosio-explorer, pull requests merged in 2019-06, with the labels that each got.

#116 Add link to smart contract name in Action history of Push action page
  src/pages/PushactionPage/components/Actionhistory.jsx
Labels: enhancement

#121 Fix a bug where calling eosio-explorer start right after eosio-explorer init would clear the local storage
  src/index.js
Labels: bug

#122 Fogbugz 3470: Start up scripts changes
  cli.sh
  init_config.file
  package.json
  pm2.js
  scripts/init.sh
  scripts/remove_dockers.sh
  scripts/start.sh
  scripts/start_gui.sh
  scripts/stop_dockers.sh
  serve.js
  src/app/App.jsx
  src/pages/InfoPage/components/Nodeswitch/Nodeswitch.jsx
  yarn.lock
Labels: enhancement

#123 Incoming doc update
  README.md
  docs/guides/permissions/import_account.md
  docs/guides/permissions/update_account.md
  docs/guides/push-action/README.md
  docs/images/permissions/accounts.png
  docs/images/permissions/create_acc_button.png
  docs/images/permissions/create_acc_panel.png
  docs/images/permissions/create_acc_result.png
  docs/images/permissions/edit_acc_after.png
  docs/images/permissions/edit_acc_before.png
  docs/images/permissions/edit_acc_mid.png
  docs/images/permissions/import_acc.png
  docs/images/permissions/import_keys_after.png
  docs/images/permissions/import_keys_before.png
  docs/images/permissions/import_single_key_after.png
  docs/images/permissions/import_single_key_before.png
  docs/images/permissions/import_single_key_mid.png
  docs/images/push-action/action-history-viewer.png
  docs/images/push-action/filter_result.png
  docs/images/push-action/success-indicator.png
  docs/pages/interact/manage-accounts-page.md
Labels: documentation
